multi-ecosystem-groups:
  infrastructure:
    schedule:
      interval: 'weekly'
updates:
  - cooldown:
      default-days: 7
    directory: '/'
    package-ecosystem: 'npm'
  - directory: '/'
    package-ecosystem: 'github-actions'
  - cooldown:
      default-days: 7
    directory: '/'
    package-ecosystem: 'uv'
version: 2
