apps:
  wiswa:
    command: 'bin/wiswa'
    plugs:
      - 'home'
      - 'network'
      - 'network-bind'
base: 'core24'
confinement: 'strict'
contact: 'https://github.com/Tatsh/wiswa/issues'
description: 'A highly opinionated way to generate and maintain projects with Jsonnet.'
donation: 'https://buymeacoffee.com/Tatsh'
grade: 'stable'
issues: 'https://github.com/Tatsh/wiswa/issues'
license: 'MIT'
name: 'wiswa'
parts:
  wiswa:
    build-packages: []
    plugin: 'python'
    python-packages:
      - '.'
    source: 'https://github.com/Tatsh/wiswa.git'
    source-tag: 'v0.3.5'
    stage-packages: []
platforms:
  amd64:
    build-on: 'amd64'
  arm64:
    build-on: 'arm64'
source-code: 'https://github.com/Tatsh/wiswa'
summary: 'A highly opinionated way to generate and maintain projects with Jsonnet.'
title: 'wiswa'
version: '0.3.5'
website: 'https://tatsh.github.io/wiswa/'
