apps:
  wiswa:
    command: 'bin/wiswa'
    plugs:
      - 'home'
      - 'network'
      - 'network-bind'
base: 'core24'
confinement: 'strict'
description: 'Generate a Python project.'
grade: 'stable'
name: 'wiswa'
parts:
  wiswa:
    plugin: 'python'
    python-packages:
      - '.'
    source: '.'
    stage-packages: []
platforms:
  amd64:
    build-on: 'amd64'
  arm64:
    build-on: 'arm64'
summary: 'Generate a Python project.'
version: '0.0.0'
